name: env_temperature_mortality
dependencies: 
  - numpy
  - pandas
  - geopandas
  - xarray
  - shapely
  - numba
  - netCDF4
  - openpyxl
  - rasterio
  - plotly
  - matplotlib
  - ipykernel
  - nbformat
  - rioxarray 