"""
Define scenario settings, ERF settings and file paths
"""

# Path to main working directory
wdir: "X:/user/liprandicn/mt-comparison/burkart2022/"
# temp_dir = "X:/user/liprandicn/Data/ERA5/t2m_daily/"
temp_dir: "X:/user/dekkerm/IMAGE_environments/IMPACTS/3_IMAGE_land/scen/SSP2_M/netcdf/"

"""
Temporal
"""

# Define temperature data source
temp_source: "MS" # MS (monthly statistics) or ERA5
# Define SSP scenario
ssp:  "SSP2" # SSP1, SSP2, SSP3, SSP5
# Set years range
start_year: 2000
end_year: 2100
# Define region classification
region_class: "IMAGE26" # "IMAGE26" or "countries"


"""
Set settings to select ERF
"""

# Choose between keeping temperature zones (False) or using single mean ERF for all zones (True)
single_erf: False
# Choose between extrapolating ERFs (True) or keeping them as in Burkart 2021 (False)
extrap_erf: False
# Choose between calculating mean RR (True), specific or random draw (False). 
draw_type: "mean"  # "mean", "random" or int (specific draw number)