# Path to working directory where all data will be stored
wdir: ""

# Path to ERA5 daily temeprature data
era5_dir: ""

# Path to IMAGE regions classification folder produced manually
regions_class: ""

# Path to LandScan population rasters
landscan_path: ""

# Path to population projections from IMAGE nc files
pop_dir: ""