# Path to working directory where all data will be stored
wdir: "X:/user/liprandicn/mt-comparison/carleton2022/"

# Path to ERA5 daily temeprature data
era5_dir: "X:/user/liprandicn/DATA/ERA5/t2m_daily/"

# Path to IMAGE regions classification folder produced manually
regions_class: "X:/user/liprandicn/mt-comparison/data"

# Path to LandScan population rasters
landscan_path: "X:/user/liprandicn/DATA/POPULATION/LandScan_Global/"

# Path to population projections from IMAGE nc files
pop_dir: "X:/user/liprandicn/DATA/POPULATION"