# Working directory (root) where input and output files are stored
wdir: "X:/user/liprandicn/mt-comparison/carleton2022/"

# Temperature data directory
temp_dir: "X:/user/dekkerm/IMAGE_environments/IMPACTS/3_IMAGE_land/scen/SSP2_M/netcdf/"
#"X:/user/dekkerm/IMAGE_environments"
#"X:/user/dekkerm/IMAGE_environments/IMPACTS/3_IMAGE_land/scen/SSP2_M/netcdf/"
# "X:/user/liprandicn/Data/ERA5/t2m_daily/" # ERA5 directory

# Income data directory
gdp_dir: None # Use default GDP scenarios

# Set years range
start_year: 2000
end_year: 2100

# Define project name and scenario
project: default
scenario: "SSP1_Carleton" #  SSP#_carleton OR SSP#_ERA5 OR IMAGE-scenario-name

# Set adaptation ON or OFF
adaptation: True

# Select regions classification
regions: "IMAGE26" # "IMAGE26" or "countries" OR "impact regions"

# Store in Reporting Tool
reporting_tool: False # No .OUT files to store
