# Working directory (root) where input and output files are stored
wdir: ""

# Temperature data directory
temp_dir: ""

# Income data directory
gdp_dir: ""

# Set years range
start_year: 2000
end_year: 2100

# Define project name and scenario
project: ""
scenario: "" #  SSP#_carleton OR SSP#_ERA5 OR IMAGE-scenario-name

# Set adaptation ON or OFF
adaptation: True